on: [push, pull_request]

name: Build

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - target: wasm32-unknown-unknown
            cfg: client
          - target: x86_64-unknown-linux-gnu
            cfg: engine
        feature:
          - brotli
          - gzip
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          targets: ${{ matrix.target.target }}
      - run: cargo check --target ${{ matrix.target.target }} --features ${{ matrix.feature }}
        env:
          RUSTFLAGS: --cfg ${{ matrix.target.cfg }}

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: rustfmt
      - run: cargo fmt --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - target: wasm32-unknown-unknown
            cfg: client
          - target: x86_64-unknown-linux-gnu
            cfg: engine
        feature:
          - brotli
          - gzip
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          targets: ${{ matrix.target.target }}
          components: clippy
      - run: cargo clippy --target ${{ matrix.target.target }} --features ${{ matrix.feature }} -- -D warnings
        env:
          RUSTFLAGS: --cfg ${{ matrix.target.cfg }}